에러(error)와 예외(Exception)

에러는 실행이 되지 않는다.
예외는 실행 도중에 발생되는 오류

예외가 발생하면 프로그램이 오동작 할 수 있다.
그래서 예외가 발생하면 오동작이 나지 않도록
처리해 줘야 한다.
이런 구문이   try catch 문법입니다.

예외는 필수적으로 처리하는 경우도 있고
하지 않아도 되는 경우가 있다.
예를 들어 Thread.sleep() 기능은
예외를 필수적으로 처리해야 하는 기능이다.

예외를 처리하는 방법은 2가지 이다.
1가지는 예외를 직접처리하는 방법
다른 한가지는 예외를 떠 넘기는 방법
떠 넘길때는 호출한 메서드에 떠 넘긴다.

try{
	//예외가 발생할 수 있는 코드

}catch (  ){
	// 발생된 예외가 처리되는 코드
}catch (  ){
	// 발생된 예외가 처리되는 코드
}finally{
	// try 구문을 빠져나갈대 실행되는 코드
	// 즉, 예외 발생 유무에 상관없이 실행
} 

예외는 실행중에 발생하는 오류이다.
이 오류가 오작동이 되는 것을 방지하기 위해서
try구문을 사용한다.
try구문은  try catch finally가 있는데
try구문은 예외를 감지한다. 예외가 발생하면 catch 에서
처리해 준다. 예외가 발생하면 아래 코드는 실행하지 않는다.
finally 구문은 try 구문을 빠져 나갈때 실행된다..













